name: "Test Suite: @nodevu/core"

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    if: github.repository == 'cutenode/nodevu'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: current
    - name: Run npm install
      run: npm install -ws
    - name: Run npm lint
      run: npm run lint