name: "Test Suite: Linter (static)"

on:
  push:
  pull_request:
    paths:
        - 'static/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    if: github.repository == 'cutenode/nodevu'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: current
    - name: Run npm install -w static
      run: npm install -w static
    - name: Run npm run lint -w static
      run: npm run lint -w static
