name: "Test Suite: Linter (earliest)"

on:
  push:
  pull_request:
    paths:
        - 'earliest/**'
    branches:
      - main
  workflow_dispatch:
  workflow_call:

jobs:
  tests:
    if: github.repository == 'cutenode/nodevu'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: current
    - name: Run npm install -w earliest
      run: npm install -w earliest
    - name: Run npm run lint -w earliest
      run: npm run lint -w earliest
